import os
import re

replacements = {
    r"'Không tìm thấy Class ID.'": r"'Class ID not found.'",
    r'"Không tìm thấy Class ID."': r'"Class ID not found."',
    r'"Lỗi tải danh sách nhóm."': r'"Failed to load team list."',
    r"'Lỗi tải danh sách nhóm.'": r"'Failed to load team list.'",
    r'"Lỗi kết nối máy chủ."': r'"Server connection error."',
    r"'Lỗi kết nối máy chủ.'": r"'Server connection error.'",
    r"'Nhóm chưa đặt tên'": r"'Unnamed Team'",
    r"'Thành viên nhóm:'": r"'Team Members:'",
    r"'Lỗi: ": r"'Error: ",
    r'"Không thể lấy thông tin điểm."': r'"Could not get grade information."',
    r"'Không thể lấy thông tin điểm.'": r"'Could not get grade information.'",
    r"'Chưa có nhận xét từ giảng viên.'": r"'No feedback from lecturer yet.'",
    r"'Nhóm \$teamName chưa có điểm số cho Lab này.'": r"'Team \$teamName does not have a grade for this Lab yet.'",
    r"'Lỗi'": r"'Error'",
    r"'Không có sinh viên nào trong danh sách lớp.'": r"'No students found in the class list.'",
    r"'Không có nhóm nào trong lớp này.'": r"'No teams found in this class.'",
    r"'Sinh viên \(Class Users\)'": r"'Students (Class Users)'",
    r"'Không thể tải lịch sử Kit của nhóm.'": r"'Failed to load team Kit history.'",
    r"'Hãy vào \"Danh sách Team\" để xem lịch sử của nhóm bạn.'": r"'Please go to \"Team List\" to view your team\'s history.'",
    r"'Nhóm chưa có lịch sử mượn trả Kit.'": r"'The team has no Kit borrowing history.'",
    r'"Nhóm chưa có lịch sử mượn trả Kit."': r'"The team has no Kit borrowing history."',
    r"'Lớp/Nhóm'": r"'Class/Team'",
    r"'Chưa trả'": r"'Not Returned'",
    r"'Đã trả'": r"'Returned'",
    r"'Không thể tải lịch sử thiết bị của nhóm.'": r"'Failed to load team equipment history.'",
    r"'Nhóm chưa có lịch sử mượn trả thiết bị.'": r"'The team has no equipment borrowing history.'",
    r'"Nhóm chưa có lịch sử mượn trả thiết bị."': r'"The team has no equipment borrowing history."',
    r"'Check-in Lịch phòng'": r"'Lab Check-in'",
    r"'Xác nhận bàn giao chìa khóa cho giảng viên'": r"'Confirm key handover to lecturer'",
    r"'Tài khoản Bảo vệ chưa được cấp quyền xem danh sách lịch \(Lỗi 403\). Vui lòng liên hệ Admin.'": r"'Security account is not authorized to view the schedule list (Error 403). Please contact Admin.'",
    r"'Không thể tải danh sách lịch: ": r"'Failed to load schedule list: ",
    r"'Đã xảy ra lỗi hệ thống.'": r"'A system error occurred.'",
    r"'Tài khoản chưa được cấp quyền xem lịch \(Lỗi 403\). Vui lòng liên hệ Backend để mở quyền.'": r"'Account is not authorized to view the schedule (Error 403). Please contact Backend.'",
    r"'Lỗi kết nối: ": r"'Connection error: ",
    r"'Không tìm thấy ID lịch hoặc phòng.'": r"'Schedule or Room ID not found.'",
    r"'Xác nhận Check-in'": r"'Confirm Check-in'",
    r"'Giảng viên: ": r"'Lecturer: ",
    r"'Xác nhận đã bàn giao chìa khóa cho giảng viên\?'": r"'Confirm key has been handed over to the lecturer?'",
    r"'Hủy'": r"'Cancel'",
    r"'✅ Check-in thành công! Lịch đã chuyển sang InProgress.'": r"'✅ Check-in successful! Schedule is now InProgress.'",
    r"'Lỗi check-in: ": r"'Check-in error: ",
    r"'Không có lịch nào chờ Check-in.'": r"'No schedules pending Check-in.'",
    r"'Không thể tải thông tin. \(Code: ": r"'Failed to load info. (Code: ",
    r"'Token hết hạn hoặc không hợp lệ \(401\)'": r"'Token expired or invalid (401)'",
    r"'Lỗi Server Backend'": r"'Backend Server Error'",
    r"'Phiên rỗng, vui lòng đăng xuất ra rồi Đăng Nhập Lại. \(": r"'Empty session, please logout and Login Again. ('",
    r"'ĐĂNG XUẤT LẠI'": r"'LOGOUT AGAIN'",
    r"'Chưa cập nhật tên'": r"'Name not updated'",
    r"'Chưa cập nhật'": r"'Not updated'",
    r"'Chưa thiết lập'": r"'Not set'",
    r"'Phiên đăng nhập không hợp lệ": r"'Invalid login session",
    r"'Không tìm thấy thông tin": r"'Information not found",
    r"'Đang xử lý...'": r"'Processing...'",
    r"'Thành công'": r"'Success'",
    r"'Thất bại'": r"'Failed'",
    r"'Đóng'": r"'Close'",
    r"'Trang chủ'": r"'Home'",
    r"'Đăng nhập'": r"'Login'",
    r"'Xác nhận'": r"'Confirm'",
    r"'Hiện không có lớp nào.'": r"'No classes currently available.'",
    r"'Không tải được danh sách lớp.'": r"'Failed to load class list.'",
    r"'Không tải được danh sách lớp'": r"'Failed to load class list'",
    r"'Hiện không có lớp nào được phân công.'": r"'No classes currently assigned.'",
    r"'Không thể tải danh sách lớp học.'": r"'Failed to load classes.'",
    r"'Không tìm thấy thông tin Sinh viên từ API.'": r"'Student information not found from API.'",
    r"'Lỗi kết nối \(Vui lòng đăng xuất & đăng nhập lại\).'": r"'Connection error (Please logout & login again).'",
    r"'Không tìm thấy thông tin lecturerId từ API.'": r"'Lecturer ID not found from API.'",
    r"'Lỗi kết nối phần lấy ID \(Vui lòng đăng xuất & đăng nhập lại\).'": r"'Connection error retrieving ID (Please logout & login again).'",
    r"'Chưa chọn ảnh checkout'": r"'Checkout image not selected'",
    r"'Lịch trình hôm nay'": r"'Today\'s Schedule'",
    r"'Lịch trình'": r"'Schedule'",
    r"'Không thể tải báo cáo hôm nay.'": r"'Failed to load today\'s report.'",
    r"'Cảnh báo hệ thống'": r"'System Warnings'",
    r"'Danh sách Slot \(Ca học\)'": r"'Slot List (Sessions)'",
    r"'Hôm nay không có ca học nào được xếp hành.'": r"'No sessions scheduled for today.'",
    r"'Ngày \$'": r"'Date \$'",
    r"'lớp học hôm nay'": r"'classes today'",
    r"'Hôm nay'": r"'Today'",
    r"'Chụp ảnh Lab'": r"'Take Lab Photo'",
    r"'Hoàn tất Check-out'": r"'Complete Check-out'",
    r"'Đang upload ảnh...'": r"'Uploading image...'",
    r"'Đang xử lý check-out...'": r"'Processing check-out...'",
    r"'Lỗi chọn ảnh: ": r"'Image selection error: ",
    r"'Lỗi upload ảnh lên Cloudinary'": r"'Error uploading image to Cloudinary'",
    r"'Check-out thành công!'": r"'Check-out successful!'",
    r"'Không lấy được URL ảnh.'": r"'Could not get image URL.'",
    r"'Vui lòng chụp ảnh Lab trước khi check-out'": r"'Please take a Lab photo before check-out'",
    r"'Lỗi: ": r"'Error: ",
    r"'Không có thiết bị/Kit nào được mượn.'": r"'No Equipment/Kit borrowed.'",
    r"'Mượn lúc: ": r"'Borrowed at: ",
    r"'Xem điểm'": r"'View Grade'",
    r"'Lịch sử thiết bị'": r"'Equipment History'",
    r"'Lịch sử Kit'": r"'Kit History'",
    r"'Nhóm chưa có lịch sử mượn trả Kit.'": r"'Team has no Kit borrowing history.'",
    r"'Nhóm chưa có lịch sử mượn trả thiết bị.'": r"'Team has no Equipment borrowing history.'",
    r"'Chưa có mô tả'": r"'No description'",
    r"'Chưa có nhận xét'": r"'No feedback'",
    r"'Trạng thái'": r"'Status'",
    r"'Không xác định'": r"'Unknown'",
    r"'Từ chối'": r"'Rejected'",
    r"'Đang mượn'": r"'Borrowing'",
}

def process_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    new_content = content
    for pattern, repl in replacements.items():
        new_content = re.sub(pattern, repl, new_content)
        
    if new_content != content:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print(f"Updated {filepath}")

for root, _, files in os.walk('lib'):
    for file in files:
        if file.endswith('.dart'):
            process_file(os.path.join(root, file))
